### ISSUE TITLE
Frontend stack decision 

### ISSUE THREAD

**Issue by vrom911** [kowainik/issue-wanted#1]
We know for sure that we'd like to use some functional language for frontend. What suits best for our needs: PureScript, Elm, other? Pros and cons?

**Comment by vrom911** [comment]
@willbasky thank you for this table! This is going to be very useful. I would like to add a couple of stuff to it. The size of the `Elm` js code is much smaller (especially in the newest release 1.19, which apparently has too much breaking changes and features cuts :( ) than any other (Puserscript, GHCJS etc.). What about the bridge, the Elm's one is very broken, unfortunately. I can't say for Purescript bridge though as I had very limited experience with it, but I guess it should be slightly better at least.

**Comment by willbasky** [comment]
I also lean toward PureScript. Will the middle JS size become a problem?

**Comment by sshine** [comment]
I only have experience with Elm, but I'm not comfortable with their development process.

I've never used PureScript or GHCJS, so I haven't experienced the disadvantages in practice.

For me, the main downside of GHCJS is the code size, and the mainside downside of PureScript is having to express your data model once on the back-end and once on the front-end. Perhaps PureScript is so similar to Haskell that you can re-use / transform the data model of one into the other. Another downside of PureScript that I've read about is that [it uses bower](https://github.com/commercialhaskell/stack/issues/2681), which is a dead package manager.

So I'd lean towards GHCJS just for the bridge, but I'd be *very* willing to hear a veto if there are any downsides I don't know of.

**Comment by ChShersh** [comment]
I don't like GHCJS because of:

* Code size
* Low amount of documentation
* Possible need to learn and use nix just to build project

After WebAssembly backend for GHCJS is implemented, it will become much better! But I would like to use frontend-specific tool for this task now. Also, again, learning purposes 🙂 

`bower` is not a great tool, but we can live with that for now.

**Comment by ChShersh** [comment]
Decided: PureScript.
