### ISSUE TITLE
Add handling of cabal file parser errors

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#102]
Currently using: 
```
parseGenericPackageDescriptionMaybe :: ByteString -> Maybe GenericPackageDescription 
```

Eventually we should use:
```
parseGenericPackageDescription :: ByteString -> ParseResult GenericPackageDescription 
```
And take advantadge of errors.

Related to #110

**Comment by rashadg1030** [comment]
@chshersh @vrom911 Actually maybe this is better left as `Maybe` to keep things simpler, we do have logging in case it is `Nothing`. Should we throw an error as well? If so, this will stop the program each time it is `Nothing` which happens a lot. I guess we can continue the program using `catchError` when an error is thrown.

**Comment by chshersh** [comment]
@rashadg1030 Logging is fine. But I guess that if you use `Result` instead of `Maybe` you should be able to log a more meaningful message.
