### ISSUE TITLE
Add functionality for associating Repo categories with the Repo

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#104]
We currently fetch the repo data from GitHub and parse the repo categories from the cabal file separately. We must now combine them to produce a whole repo that can be stored in the DB.

Blocked by #119

**Comment by rashadg1030** [comment]
Had some questions about writing the function that would solve this issue:
```
fromGitHubRepo :: GitHub.Repo -> Repo
fromGitHubRepo githubRepo = Repo
    { repoOwner      = RepoOwner $ GitHub.untagName $ GitHub.simpleOwnerLogin $ GitHub.repoOwner githubRepo
    , repoName       = RepoName  $ GitHub.untagName $ GitHub.repoName githubRepo
    , repoDescr      = fromMaybe "" $ GitHub.repoDescription githubRepo
    , repoCategories = SqlArray []
    }
```
For `repoCategories` we have an empty array. I remember the idea of inserting the `repos` with an empty `categories` field and then populating the rows with categories after. Are we still doing that? We could construct the `repos` in the `MonadCabal` monad:

```
fromGitHubRepo :: MonadCabal m => GitHub.Repo -> m Repo
fromGitHubRepo githubRepo = do ...
```
Is this fine??

**Comment by chshersh** [comment]
@rashadg1030 Hard to tell without benchmarking and seeing how much time syncing the cache actually works. We're using `executeMany` to fetch to the database, so I expect this query to perform really fast even for a huge amount of data. However, if now you need to download a file for each `Repo` before inserting to the database, the performance of sync can decrease by a lot. Well, by _a lot_ is a vague here. If it becomes 5 minutes instead of 20 seconds, this is still fine. If it's 2 hours instead of 5 minutes then this is not that good.

**Comment by rashadg1030** [comment]
@chshersh If we do decide to populate the repo table with categories after inserting the repos, how would we do this? We would have to attach extra information to the categories in order to associate them with the correct repo, right? Or is there a better way?

**Comment by chshersh** [comment]
@rashadg1030 After you fetch all repos, you have `[Repo]`. Given a `Repo` you can write a function:

```haskell
updateRepoCategories :: Repo -> m ()
```

All you need to do is to just call `mapM_ updateRepoCategories repos`. And if we want to update them concurrently, you just replace `mapM_` with `mapConcurrently`

**Comment by rashadg1030** [comment]
I'm using this algorithm: 
1. `fetchAllHaskellRepos :: (... m) => m [GitHub.Repo]`
2. Map `fromGitHubRepo :: GitHub.Repo -> Repo` over the list from above.
3. Write `[Repo]` to DB.
4. Use `mapM_ updateRepoCategories repos` to update them.
