### ISSUE TITLE
Implement `MonadDownload` effect

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#105]
This effect should take `RepoOwner` and `RepoName`, construct a URL for corresponding `.cabal` file, try to download the file and throw the error in case of unsuccess.

This involves multiple steps:

1. Create `IW.Effects.Download` module
2. Introduce the following typeclass there:
```haskell
class Monad m => MonadDownload m where
    downloadFile :: Text -> m ByteString  -- probably better type for URL can be used instead of Text
```
3. Add `Manager` field to `Env` data type
4. Implement `Has` instance for `Env` and `Manager`
5. Implement `MonadDownload` for `App` in terms of `Has Manager` and `WithError m`

See implementation details here:

* https://github.com/kowainik/issue-wanted/issues/43#issuecomment-509884577

**Comment by rashadg1030** [comment]
@chshersh Awesome👍🏽 I’m looking forward to implementing a custom effect.

**Comment by rashadg1030** [comment]
@chshersh I think we should have an `URL` type, so I'll implement that first. Is that fine? I'll open an issue for it.

**Comment by chshersh** [comment]
@rashadg1030 Yeah, that's fine. Also, let's name it `Url` according to the naming scheme in our style guide.
