### ISSUE TITLE
Implement `MonadCabal` effect for extracting relevant fields of the `.cabal` file

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#106]
Blocked by #105 

Once `MonadDownload` is implemented, it should be possible to implement:

```haskell
class Monad m => MonadCabal m
    getCabalCategories :: RepoOwner -> RepoName -> m [Category]
```

An instance of this effect for `App` should do the following:

1. Construct URL to `.cabal` file by `RepoOwner` and `RepoName`
2. Download the file.
3. Try to parse it and return a list of categories from this file.

**Comment by rashadg1030** [comment]
@chshersh Okay so I see number 2 is Download the file. Does this mean `MonadDownload m` should be a superclass of `MonadCabal m`?
```  
class MonadDownload m => MonadCabal m
    getCabalCategories :: RepoOwner -> RepoName -> m [Category]
```

**Comment by chshersh** [comment]
@rashadg1030 

> Does this mean MonadDownload m should be a superclass of MonadCabal m?

Not necessary.  Down the road, if we want to introduce mocking for testing, we can have a pure implementation of `MonadCabal` that just returns hardcoded `.cabal` file in pure context without downloading anything.

**Comment by rashadg1030** [comment]
@chshersh Okay yeah that's a good point. It's actually better for prototyping if it isn't constrained to `MonadDownload` because we can use it with other monads if needed.
