### ISSUE TITLE
Implement proper pagination

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#114]
In our case pagination should be implemented on the backend because we have a lot of issues. Every query that returns issues, should end with the following:

```sql
LIMIT ISSUES_PER_PAGE
OFFSET (PAGE_NUMBER * ISSUES_PER_PAGE)
```

Where:

1. `ISSUES_PER_PAGE` is hardcoded constant (like 100)
2. `PAGE_NUMBER`: this is what frontend gives to backend

**Comment by rashadg1030** [comment]
@chshersh Should pagination be implemented for `repos` as well?

**Comment by rashadg1030** [comment]
@chshersh I added pagination for repos too
