### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#122]
Fix endpoints and other minor cleanups.

**Comment by rashadg1030** [comment]
@vrom911 @chshersh  I have to update the README with a few things in order to submit his project for GSoC. I'm doing this soon.

**Comment by chshersh** [comment]
@rashadg1030 I guess you can also add links to your blog posts in a section like "Architecture description" or "Detailed description of the implementation". I think that it would be nice to have links to the relevant blog posts about this project in `README` as well.

**Comment by rashadg1030** [comment]
@chshersh Good idea 👍
