### ISSUE TITLE
Choose shorter name for `IssueWanted` prefix

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#14]
All modules currently have `IssueWanted` prefix in the library. Let's choose shorter prefix until it's not to late :slightly_smiling_face:

**Comment by willbasky** [comment]
`IW`
`iw`

**Comment by StarWonder67** [comment]
IsWanted
Iwant

**Comment by chshersh** [comment]
Decided on `IW`.

**Comment by rashadg1030** [comment]
This is a good idea. I'll do this first before I start pushing any code. I'll change the prefix from `IssueWanted` to `IW`.
