### ISSUE TITLE
Database decision

### ISSUE THREAD

**Issue by ChShersh** [kowainik/issue-wanted#2]
We should decide which Database we want to use for `issue-wanted`. We don't need something strong and secure but we also don't want 💩 

Possible candidates:

* PostgreSQL
* SQLite
* RocksDB
* `acid-state`
* Raw files

Something else?

What we need to store (approximation of our database scheme):

* List of issues for beginners for every Haskell GitHub repository
* GitHub issue metadata (name, tags?, creation date, something else (to sort issues))
* Categories for every project
* Users metadata (GitHub nickname, achievements)

Looks like some SQL DB is the solution to go... But in that case we also need to choose library...

**Comment by willbasky** [comment]
I am not an expert in DB, just watched the lecture about `HaSql` library for work with `PostgreSQL` and know that [Swarm](https://github.com/ff-notes/swarm) implemented by Yuriy Syrovetskiy to syncronize without any data lost.

**Comment by ChShersh** [comment]
I would like to use `SQLite` because it's very simple and lightweight. As I learned today, it's good only when you have a lot of reads and low number of writes. And we will have a lot of writes to our database because we're going to constantly sync with GitHub. So I'm voting for PostgreSQL as the most reliable option. There're several libraries we can consider:

* [`postgresql-simple`](http://hackage.haskell.org/package/postgresql-simple): very straightforward to use
* [`squeal`](https://github.com/morphismtech/squeal): ORM for PostgreSQL. Uses a lot of type-level magic.
* [`beam`](https://github.com/tathougies/beam): another decent ORM for PostgreSQL (but not only).

Both ORM libraries look the same to me. But if we go with ORM,I would recommend `squeal`: at least the library author seemed like a more responsive and pleasant maintainer.

**Comment by willbasky** [comment]
ORM is better, isn`t it?

`postgresql-simple` isn`t type-safe for queries,is it? (as HaSQL i guess)

**Comment by sshine** [comment]
I've also just recently seen a talk on Hasql. It seemed like a good library. The documentation is limited.

I've never used an ORM in Haskell, but squeal seems type-safe and well-explained.

**Comment by ChShersh** [comment]
I've heard about `Hasql`. It's a relatively popular library. The reason for choosing `squeal` is to learn something new and try new technologies. And if we weren't satisfied, we can always switch to different library 🙂

**Comment by ChShersh** [comment]
Decided: PostgreSQL + `squeal`.
