### ISSUE TITLE
Graphql integration and github apis: V3 or V4? 

### ISSUE THREAD

**Issue by Infi-Knight** [kowainik/issue-wanted#21]
Which version of Github API are we going to use?
Github provides access both in the form of REST(v3) and GraphQl(v4). Considering the amount of data we need to scrap for issues, cabal files and keeping our database synced with repos would it be beneficial to integrate graphql in backend as well as frontend? A single graphql call will replace multiple REST calls thus reducing latency with database as well as frontend and keep the rate limits imposed by github under check.

**Comment by ChShersh** [comment]
I can see how rate limit can be a problem for synchronisation. There's Haskell library for writing GraphQl queries:

* https://github.com/haskell-graphql/graphql-api

Let's have this issue open and think more about that part of the application.

**Comment by Infi-Knight** [comment]
"graphql-api" seems in a nascent stage and mentions unstable API, though I am unsure about it's suitability to the project, given my limited exposure to Haskell ecosystem. Maybe we can take an iterative approach and introduce Graphql at a later point of time.

**Comment by Infi-Knight** [comment]
We don't need GraphQL integration just to query information from GitHub, because we can simply send POST requests from our server sending along a graphql query. Then we can parse the resulting json and use it as we deem fit. But this means that `phadej/github` will not prove to be much help as it uses v3. GraphQL integration is required only for efficient communication between frontend and server .

**Comment by chshersh** [comment]
@rashadg1030  we need to discuss are we going to use GraphQL or `phadej/github` library for querying GitHub API.

**Comment by rashadg1030** [comment]
@chshersh I'm still not sure what the best option is yet. I would like to discuss with someone more experienced about the tradeoffs between using GraphQL and REST to query an API. When I did some research into the `graphql-api` library it seemed to lack support for querying GraphQL APIs, but maybe I didn't look hard enough. `phadej`'s `github` library, on the other hand, seems pretty straightforward to use and the documentation on hackage is pretty good. It's important to note that `github` library doesn't have functions for every GitHub API endpoint. Anyways, I would like to talk more in-depth with someone before I come to a conclusion.

**Comment by chshersh** [comment]
@rashadg1030 After thinking a little bit on this I propose to use `github` library. I don't have any experience with GraphQL and I never heard about anyone using Haskell library for GraphQL. I don't think that the rate limit is important for us. Basically, we only need to do only two API queries:

1. Search for all GitHub Haskell repos.
2. Search for all GitHub Haskell open issues.

[Rate limit for search API](https://developer.github.com/v3/search/#rate-limit) is 30 requests per minute. More than enough for us 🙂

**Comment by Infi-Knight** [comment]
I think there is another alternative. We can use both REST and GraphQL. For basic endpoints we can hit the REST ones and for others hit /api/graphql, depending upon support provided by graphql library

**Comment by rashadg1030** [comment]
@chshersh I think `github` library is the better choice. Any queries that aren't covered by `github` library can be implemented using `servant-client` if needed. @Infi-Knight A hybrid approach may be nice, but I think it is too complex to have two separate ways of querying the GitHub API. GraphQL shines when making complex, nested queries, but as @chshersh  mentioned we will only be fetching Haskell repos and Haskell open issues. The `github` library provides this functionality and is simpler than using GraphQL.

**Comment by chshersh** [comment]
Then it's decided. Let's stick to the `github` library.
