### ISSUE TITLE
Preferred issue update channels - webhooks?

### ISSUE THREAD

**Issue by dylan-thinnes** [kowainik/issue-wanted#23]
Hi all, I'm looking at trying this for Google Summer of Code. Currently in the `fetch` functions in `IssueWanted.Search`, we can poll Github's API for issues regularly. Is this the permanent plan for keeping the cache up to date?

I ask because I've been prodding around the `github` library, and was wondering as to the value of using webhooks to subscribe to particularly active repos (e.g, `stack`) to give more live updates on issues with valuable tags.

@ChShersh Do you have any specific recommendations on how we want to keep items synced?

**Comment by ChShersh** [comment]
@dylan-thinnes There are no plans to support real-time live updates for the `issue-wanted` project. Main goal is not help implementing issues as fast as possible, but improve discoverability of what can be done. And, honestly, most issues take time for discussing and coming out with the plan. Implementing `issue-wanted` as a GitHub application with the webhook subscription system will be more complicated and will require to add this application to every Haskell project first. Maybe in some future it could be remade into GitHub App but for now it's more like a GitHub scraper.
