### ISSUE TITLE
Decide on the Haskell database library

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#27]
Possible candidates:

* `postgresql-simple`
* `squeal`
* `opaleye`
* `esqueleto`

@rashadg1030 needs to make the decision with which of the library he prefers to work. But we can share our thoughts on the libraries and discuss the options.

**Comment by rashadg1030** [comment]
I'm leaning heavily towards `postgresql-simple` because it is the simplest solution and I have used it before. The other libraries are more powerful than `postgresql-simple`, but I don't think it will be worth the complexity.

**Comment by chshersh** [comment]
@rashadg1030 thanks for your thoughts! Good decision, I appreciate it 👍
I will create several follow up issues to be done next week.
