### ISSUE TITLE
Bring `three-layer` architecture to issue-wanted

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#29]
See the [`three-layer`](https://github.com/holmusk/three-layer) repository for example. 

Specifically, we need to bring the following things:

- [x] Our custom monad with the environment (see `Lib/App` directory)
- [x] Error data types with helper functions (see `Lib/App/Error.hs` module)
- [x] `Effects.Log` module with logging
- [x] TOML configuration
- [x] Makefile for running commands smoothly

**Comment by rashadg1030** [comment]
Should I copy the file structure of `three-layer` as well? I'm thinking of putting the `IW` folder in a `Lib` folder. Right now the `IW` folder is a direct child of the `src` folder.

**Comment by chshersh** [comment]
@rashadg1030 `Lib` is a placeholder name. In our case `Lib` should be replaced with `IW`.

**Comment by rashadg1030** [comment]
I had to import `pattern E` and `log` from `Colog` to get this module to compile. In the `three-layer/src/Lib/Effects/Log.hs` example I don't see these imports. What am I missing?

**Comment by chshersh** [comment]
@rashadg1030 See my comment under commit: https://github.com/kowainik/issue-wanted/commit/f905e31e87105da2c828529726f2a0f8aa5d5d70#commitcomment-33868656
