### ISSUE TITLE
Describe SQL schema for storing data

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#30]
What needs to be done here:

- [x] Schema should be written in raw SQL files in the `sql/` directory in the project root. This directory should contain two files now: `schema.sql` with the schema and `drop.sql` with removing the schema (useful for testing)
- [x] `IW.Db.Schema` module with helper functions (see `three-layer` for the example)

**Comment by rashadg1030** [comment]
I want to work on the schema but I'm not sure what the shape of our data is. Any suggestions? I have some ideas that I will post later.

**Comment by chshersh** [comment]
@rashadg1030 You can start from seeing what GitHub API provides and think of possible tables and columns that can be relevant. So you can start with something and improve the schema later during the work when we realise that we need something more.

**Comment by rashadg1030** [comment]
@chshersh Okay so I'm thinking we have two tables: `repos` and `issues`. I think issues should be related to repos using a foreign key. Each issue will have a repo id as a foreign key. Or should we just keep the two tables separate and ignore the relationship. Which is better?

**Comment by chshersh** [comment]
@rashadg1030 I think your proposal is good :+1: The only difficult question here is to how store labels for issues and categories for repos so they can be filtered efficiently. Note, that issues may change their labels, some labels can be renamed and we want to keep up-to-date information in our DB. So there should be some way to update this information.

**Comment by rashadg1030** [comment]
@chshersh The best solution I can think of for storing labels with issues is storing the `label_url` for each issue in the DB. I just need to add a `label_url` field to the issues table. The server can use the `label_url` to get all labels for an issue. Or that can be done by the frontend. The frontend could ask the server for a `label_url`, make a request for labels using the url, and then display it.

**Comment by rashadg1030** [comment]
@chshersh For repository categories I'm not sure. By repository "category" do you mean GitHub [topics](https://help.github.com/en/articles/classifying-your-repository-with-topics)? Do you mean the hackage category the package belongs to? Or will we have our own categories for repositories somehow?

**Comment by rashadg1030** [comment]
@chshersh I just read this article on handling many-to-many relationships in a DB. We could uses a `join table` to associate `issues` with `labels`. [Link](https://dzone.com/articles/how-to-handle-a-many-to-many-relationship-in-datab)
