### ISSUE TITLE
Add `Dockerfile`

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#39]
After adding the `Makefile` I realized that the project uses docker to run the PostgreSQL database. Is the `Dockerfile` going to be the same as the one in the `three-layer` repo?

**Comment by chshersh** [comment]
@rashadg1030 Most likely. But we can always create our own docker image and corresponding `Dockerfile`. Don't worry about that for now, we will get to this part once we configure infrastructure and all that stuff.
