### ISSUE TITLE
Issue-wanted endpoint URLs

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#46]
What should the URLs for `issue-wanted` look like? So far, we have one endpoint:
`~/issues/:issueId`

Some other ones I think we need:

```
~/issues/         -- returns all issues
~/issues/:label   -- returns all issues with the given label 
~/repos/          -- returns all repos
~/repos/:repoId   -- returns a repo with the Id
~/repos/:category -- returns all repos with the given category
```

Any more suggestions?

**Comment by chshersh** [comment]
For now we are interested only in the following endpoints:

1. Get all issues (sorted by some default parameters)
2. Get all issues that have a label or category from the given list (filtering).

All queries should also take limit with default value (like 100) (we don't want to give 150K issues each time). Pagination will be implemented later.

**Comment by rashadg1030** [comment]
@chshersh Sort parameter examples:
`~/issues?sort=title:asc` Sort by issue title ascending order
`~/issues?sort=id:desc`  Sort by issue id descending order
`~/issued?sort=id:asc&label=good first issue` Sort by ascending issue id and has label good first issue

Is there any more that will be helpful?

**Comment by rashadg1030** [comment]
My next goal is to add a limit query parameter maybe? How will we do pagination?
