### ISSUE TITLE
Update the schema for more efficiency and simplicity

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#54]
I did some research on how to structure the database for our use case better. We need to do some adjustments to make it work fast. At the same time, it will make our lives easier.

1. Foreign key in the `issues` table should be not for id but for `repo.name`. It's completely okay to have textual foreign keys. Just add an INDEX for `repos.name` column (later we can see what columns we are using so we can add more indexes for performance).
    * https://www.postgresql.org/docs/9.1/sql-createindex.html
2. Remove tables `categories`, `labels`, `repos_categories` and `issues_labels`. Instead, we will store them as a separate column using [PostgreSQL arrays](https://www.postgresql.org/docs/9.1/arrays.html). This approach is much much faster than joining tables. And such arrays support all operations that we need for filtering. This also means that updating labels is now a simple task: just write new labels in place for that array.

**Comment by rashadg1030** [comment]
Got it. I will work on this and ask if I have any questions. I've never heard of PostgreSQL arrays before but it seems useful.

**Comment by rashadg1030** [comment]
Also one question. For the `Issue` instead of `repoId :: Id Repo` should we have a type `repoName :: Name Repo` or something like that?

**Comment by rashadg1030** [comment]
Another question. I can't make `repo.name` a foreign key unless I add a `UNIQUE` constraint to it. GitHub repository names aren't unique right?

**Comment by chshersh** [comment]
> For the Issue record, instead of repoId :: Id Repo should we have a type repoName :: Name Repo or something like that?

We will have `Id` in almost every data type. But I don't think we will have many names. Once we have `Repo` data type with fields, we can introduce our own `Name` newtype similar to `Id`. But for now `Text` should work.

> I can't make repo.name a foreign key unless I add a UNIQUE constraint to it. GitHub repository names aren't unique right?

Okay, in that case, let's add `owner` column to the `issues` table and have a foreign key for pair. See how it's done here:

https://stackoverflow.com/questions/25564036/is-it-possible-to-create-a-foreign-key-pair-sql

**Comment by rashadg1030** [comment]
Got it👍🏽
