### ISSUE TITLE
Update Issue type

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#57]

**Comment by rashadg1030** [comment]
Is there a `ToRow`/`FromRow` instance for type `[a]`, or do I have to roll my own. The `Issue` type has a `labels :: [Text]` field. How do we get this to an SQL array?

**Comment by rashadg1030** [comment]
https://www.stackage.org/haddock/nightly-2019-06-27/postgresql-simple-0.6.2/Database-PostgreSQL-Simple-Types.html 
I think I found something `newtype PGArray a`

**Comment by chshersh** [comment]
@rashadg1030 Yes, for arrays you need to use `PGArray` newtype

**Comment by rashadg1030** [comment]
@chshersh  Okay so `Issue` now has a `PGArray Text` field. I have a `ToJSON` instance for `Issue`. I'm trying to roll the `FromJSON` instance, but I was thinking if we even need an instance because we're using the `github` api. Maybe we still need it for something else though

**Comment by rashadg1030** [comment]
```
instance (ToJSON a) => ToJSON (PGArray a) where
  toJSON :: PGArray a -> Value 
  toJSON = toJSON . fromPGArray
```
I get an orphan instance warning. It's telling me to either:
```
 move the instance declaration to the module of the class or of the type, or
 wrap the type with a newtype and declare the instance on the new type.
```

**Comment by chshersh** [comment]
@rashadg1030 We don't need `FromJSON` instance. Regarding the problem with `ToJSON` instance: you can store a plain list of values inside the `Issue` data type and wrap it in `PGArray` only in the `ToRow/FromRow` instances. This means that you cannot derive those instances automatically, you need to write them manually. But what can be done... You either need to write manual JSON or Row instances. And let's not have orphan instances. Manual wrapping and unwrapping is better for the maintainability.
