### ISSUE TITLE
Choice of web-framework

### ISSUE THREAD

**Issue by sshine** [kowainik/issue-wanted#6]
There are several web-frameworks to choose from.

I have not tested web-frameworks for two years, but the ones I came to like back then were:

- `snap` for being quite modular and not too magical.
- `scotty` for being minimalist.
- `servant` for being type-driven.

The drawbacks I can think of are: `snap` may require heavier lock-in / investment in the framework (writing *snaplets* when necessary), `scotty` may require us to learn web-framework organization the hard way if the site grows beyond its original intent, and `servant` would, I think, require a web-app-like front-end and give less of a website feel.

Maybe this issue hasn't been posted because there is an implicit answer already?

**Comment by ChShersh** [comment]
We're going to use `servant` to write backend API endpoints. It's quite nice DSL for Web API. And our frontend will be written with the help of tool that we will choose under #1 issue (which is probably going to be PureScript).

**Comment by ChShersh** [comment]
Decided: `servant`.
