### ISSUE TITLE
Add DB functions that operate within IO monad instead of entire App monad for testing

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#63]

**Comment by rashadg1030** [comment]
Is this a good idea? I think I mentioned this in the `async-worker` pull request, but I found this helpful for testing the DB functions without running the whole app.

**Comment by chshersh** [comment]
@rashadg1030 It's a good idea. Usually we implement this in the following way:

1. Have a function to creating testing environment in GHCi:
```haskell
mkGhciEnv :: IO AppEnv
```
2. Now from GHCi you can use this function to call other functions that work with `App` monad:

```haskell
ghci> env <- mkGhciEnv
ghci> runAppLogIO env $ myFunction arg1 arg2
```

**Comment by rashadg1030** [comment]
Okay great, I will do this then.
