### ISSUE TITLE
Change name of owner column in issues table

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#70]
```
CREATE TABLE IF NOT EXISTS issues
( id        SERIAL PRIMARY KEY 
, number    INT    NOT NULL
, title     TEXT   NOT NULL
, body      TEXT
, url       TEXT   NOT NULL
, owner     TEXT   NOT NULL
, repo_name TEXT   NOT NULL
, labels    TEXT   ARRAY
);
```

I was wondering if we should change the name of the `owner` column to `repo_owner`?

**Comment by chshersh** [comment]
@rashadg1030 Yeah, for consistency it's better to rename to `repo_owner`. You can even prefix all foreign keys with the full table name to make code clearer.
