### ISSUE TITLE
Add created_at and updated_at columns to repos and issues tables

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#73]
These columns should exist only inside the database. They should set to `NOW()` during creation. And `updated_at` should be updated automatically when we update the row. These columns will be useful later when we want to perform cleanup of our database.

**Comment by rashadg1030** [comment]
https://www.revsys.com/tidbits/automatically-updating-a-timestamp-column-in-postgresql/

Using the information in this link as a guide.
