### ISSUE TITLE
Remove URL field from Issue schema

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#78]
I noticed something important:
```
CREATE TABLE IF NOT EXISTS repos
( id         SERIAL PRIMARY KEY  
, owner      TEXT   NOT NULL       
, name       TEXT   NOT NULL
, descr      TEXT   NOT NULL
, categories TEXT   ARRAY
);

CREATE TABLE IF NOT EXISTS issues
( id         SERIAL PRIMARY KEY 
, number     INT    NOT NULL
, title      TEXT   NOT NULL
, body       TEXT   NOT NULL
, repo_owner TEXT   NOT NULL
, repo_name  TEXT   NOT NULL
, url        TEXT   NOT NULL
, labels     TEXT   ARRAY
);
```
For `repos` table we don't have an `url` field because we agreed we could construct the URL on the frontend with the `owner` and `name`.

The `issues` table does have an `url` field but we could remove it like `repos`.

```
-- | Data type representing a GitHub issue.
data Issue = Issue
    { issueId        :: Id Issue
    , issueNumber    :: Int
    , issueTitle     :: Text
    , issueBody      :: Text
    , issueRepoOwner :: RepoOwner
    , issueRepoName  :: RepoName
    , issueUrl       :: Text
    , issueLabels    :: SqlArray Text
    } deriving stock (Generic, Show, Eq)
      deriving anyclass (ToJSON, FromRow, ToRow)
```

```
-- | Data type representing a GitHub repository
data Repo = Repo 
    { repoId         :: Id Repo
    , repoOwner      :: RepoOwner
    , repoName       :: RepoName
    , repoDescr      :: Text
    , repoCategories :: SqlArray Text
    } deriving stock (Generic, Show, Eq)
      deriving anyclass (ToJSON, FromRow, ToRow)
```
Notice the `Repo` type doesn't have `url` either. Which one is better? Construct the URL on the frontend, backend, or store it in the database?

**Comment by chshersh** [comment]
@rashadg1030 I think it's better to not store `url` in the database and as a field of a data type. If the value of this field can be derived from existing types, usually it's better to save some storage space and just have functions like:

```haskell
repoUrl :: Repo -> Text
issueUrl :: Issue -> Text
```

These are simple pure functions and their result can be calculated extremely fast. You need to cache results of functions inside DB only if the computation of such fields is an expensive operation.
