### ISSUE TITLE
Implement types for github library errors

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#96]
The `github` library has an `Error` type that may be returned instead of a `SearchResult`. 
https://hackage.haskell.org/package/github-0.22/docs/GitHub-Data-Definitions.html#t:Error
Should we have a way of handling these errors in the App monad?

**Comment by rashadg1030** [comment]
If so how do we do this? I think we would need a new `AppErrorType`.

**Comment by chshersh** [comment]
@rashadg1030 We can add new constructor to `AppErrorType`, this is not a problem :+1:

**Comment by rashadg1030** [comment]
Ok yeah a new constructor :+1:

**Comment by rashadg1030** [comment]
@chshersh Should I had a new constructor like: 
```
-- | App errors type.
newtype AppErrorType = InternalError IError
                     | GitHubError GError
    deriving (Show, Eq)

data GError = ...
```
The `github` `Error` docs can be found here:
https://hackage.haskell.org/package/github-0.22/docs/GitHub-Data-Definitions.html#t:Error

**Comment by chshersh** [comment]
@rashadg1030 Yeah, this looks good :+1:
